service: jobi-api-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

functions:
  getCursos:
    handler: app/curso-handler.getCursos
    events:
      - http:
          path: /cursos
          method: GET
          cors: true
