service: jobi-api-service

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.8
  environment:
    MONGO_SECRET: arn:aws:secretsmanager:us-east-1:394753831255:secret:mongodb/service-user/credentials-nisjOX
  iam: ${file(iam.yml)}

plugins:
  - "serverless-python-requirements"

functions:
  - ${file(app/app.yml)}

resources:
  - ${file(resources.yml)}

package:
  patterns:
    - "!.git/**"
    - "!.github/**"
    - "!.ipynb_checkpoints/**"
    - "!services/*.ipynb"
    - "!.pytest_cache/**"
    - "!.vscode/**"
    - "!node_modules/**"
    - "!package.json"
    - "!package-lock.json"
    - "!__pycache__/**"
    - "!*.ipynb"
