service: jobi-api-service

#frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.8
  #region: ${opt:region, "us-east-1"}
  environment: ${file(environment.yml)}
  iam: ${file(iam.yml)}

plugins:
  - "serverless-python-requirements"

functions:
  getCursos:
    handler: app/curso-handler.getCursos
    events:
      - http:
          path: /cursos
          method: GET
          cors: true

resources:
  - ${file(resources.yml)}

package:
  patterns:
    - "!.git/**"
    - "!.github/**"
    - "!.ipynb_checkpoints/**"
    - "!services/*.ipynb"
    - "!.pytest_cache/**"
    - "!.vscode/**"
    - "!node_modules/**"
    - "!package.json"
    - "!package-lock.json"
    - "!__pycache__/**"
    - "!*.ipynb"
