getCursos:
  handler: app/curso.getCursos
  events:
    - http:
        path: /cursos
        method: GET
        cors: true

getCurso:
  handler: app/curso.getCurso
  events:
    - http:
        path: /cursos/{cursoId}
        method: GET
        cors: true
